import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import * as fal from '@fal-ai/serverless-client';

dotenv.config();

/**
 * Generate and download AI images from Fal.ai Flux Schnell
 * @param {Object} options
 * @param {Array} options.searchTerms - Array of image prompts for each segment
 * @param {string} options.outputDir - Directory to save downloaded clips
 * @param {string} options.jobId - Unique job identifier
 * @param {string} options.orientation - Video orientation (portrait, landscape)
 * @returns {Array} Paths to downloaded image clips
 */
export async function fetchStockFootage({ searchTerms, outputDir, jobId, orientation = 'portrait' }) {
    if (!process.env.FAL_KEY) {
        throw new Error('FAL_KEY is missing from environment variables.');
    }

    const clips = [];

    // Fal.ai specific aspect ratio strings
    const imageSize = orientation === 'portrait' ? 'portrait_16_9' : 'landscape_16_9';

    for (let i = 0; i < searchTerms.length; i++) {
        const prompt = searchTerms[i];

        try {
            console.log(`[stockFetcher] Submitting Fal.ai Flux Schnell generation task ${i + 1}/${searchTerms.length}...`);

            // Clean prompt of any special characters that might break the API
            const cleanPrompt = prompt.replace(/[^a-zA-Z0-9\s,.-]/g, '');

            // For complex anatomy, Flux requires extremely explicit positive instruction rather than negative constraints
            let enhancedPrompt = cleanPrompt;
            if (cleanPrompt.toLowerCase().includes('missing arm') || cleanPrompt.toLowerCase().includes('one arm')) {
                enhancedPrompt += ", he has only one arm. His left shoulder is completely bare and flat. The left sleeve of the jersey hangs loose and empty. Only his right arm is visible.";
            }

            enhancedPrompt += ", masterpiece, cinematic lighting, highly detailed, photorealistic, 8k resolution, uncropped face";

            // Reverting to Flux Schnell for maximum profit margins since 'Dev' still struggles with amputations
            const result = await fal.subscribe("fal-ai/flux/schnell", {
                input: {
                    prompt: enhancedPrompt,
                    image_size: imageSize,
                    num_inference_steps: 4,
                    num_images: 1,
                    enable_safety_checker: true,
                    sync_mode: true
                },
                logs: true,
                onQueueUpdate: (update) => {
                    if (update.status === "IN_PROGRESS") {
                        update.logs.map((log) => log.message).forEach(console.log);
                    }
                },
            });

            console.log(`[stockFetcher] Reading output for image ${i + 1}...`);
            let savedPath = null;
            const imagePath = path.join(outputDir, `${jobId}_image_${i}.png`);

            if (result && result.images && result.images.length > 0) {
                const imageUrl = result.images[0].url;

                // Fetch the image payload from the Fal CDN and save it to disk
                const response = await fetch(imageUrl);
                const arrayBuffer = await response.arrayBuffer();
                const buffer = Buffer.from(arrayBuffer);

                fs.writeFileSync(imagePath, buffer);
                savedPath = imagePath;
                console.log(`[stockFetcher] Successfully saved Fal.ai Flux image ${i + 1} to disk`);
            }

            if (!savedPath) {
                throw new Error("No valid image URL returned from Fal.ai.");
            }

            clips.push({
                path: savedPath,
                searchTerm: prompt,
                isImage: true,
                index: i
            });
        } catch (err) {
            console.error(`[stockFetcher] Failed to generate Fal.ai image for "${prompt}":`);
            console.error(err);
            // Continue with other clips even if one fails
        }
    }

    if (clips.length === 0) {
        throw new Error('No AI images could be generated by Fal.ai');
    }

    return clips;
}